/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"

#include "uart.h"
#include "rtc.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	char str1[24], str2[20];
		RTC_Date d, dt = {.Date = 31, .Month = 12, .Year = 23, .WeakDay=7};
		RTC_Time t, tm = {.Hours = 23, .Minutes = 59, .Seconds = 40};
		SystemInit();
		UartInit(BAUD_9600);
		RTC_Init(&dt,&tm);
		DelayMs(2000);
		//UartPuts("Hello Everybody\r\n");
		while(1)
		{
			RTC_GetTime(&t);
			RTC_GetDate(&d);
			sprintf(str1,"DT=%02d-%02d-%02d W=%d\r\n",d.Date,d.Month,d.Year,d.WeakDay);
			UartPuts(str1);
			sprintf(str2,"TM=%02d:%02d:%02d\r\n",t.Hours,t.Minutes,t.Seconds);
			UartPuts(str2);
			DelayMs(1000);
		}
		return 0;
	}
