/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"
#include "uart.h"
#include "led.h"
#include "switch.h"


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

extern int count;

int main(void)
{
	char scount[50];
	int cState = 0;
	int pState = 0;
	char str[50];

	extern int count;

	int main(void)
	{
		char scount[50];
		int cState = 0;
		int pState = 0;
		char str[50];

		SystemInit();
		LedInit(LED_ORANGE);
		UartInit(BAUD_9600);
		SwitchInit(SWITCH);
		UartPuts("1. RED LED ON\r\n");
		DelayMs(50);
		UartPuts("2. RED LED OFF\r\n");
		DelayMs(50);
		UartPuts("3. BLUE LED ON\r\n");
		DelayMs(50);
		UartPuts("4. BLUE LED OFF\r\n");
		DelayMs(50);
		UartGets(str);
		DelayMs(5);

		int i = 0;
		int choice = choice * 10 + (str[i] - 48);

		UartPuts(choice);
		DelayMs(5);
		//int res1 = atoi(str1);
		switch(choice)
		{
			UartPuts(choice);
			DelayMs(5);
			case 1:
				LedOn(LED_RED);
				break;
		}

	return 0;
}
}
